[[plugins]]
repo = 'arcticicestudio/nord-vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'junegunn/fzf'
build_on = '''
./install -all
'''

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'markonm/traces.vim'

[[plugins]]
repo = 'skanehira/translate.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = "release"

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
